name: my_tts_app
description: High Quality AI TTS
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # यह प्लगइन AI वॉइस को प्रोसेस करेगा
  piper_tts: ^0.1.0 

flutter:
  uses-material-design: true
  assets:
    - assets/hindi_voice.onnx
