name: my_tts_app description: High 
Quality TTS version: 1.0.0+1 
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    piper_dart: ^0.1.0 

flutter:
  uses-material-design: true
